@echo off
echo Starting SecureVault Network Demo...
echo.
echo Opening server in new window...
start "SecureVault Server" cmd /k "cd /d %~dp0.. && python network/socket_server.py"
echo Waiting 3 seconds for server to start...
timeout /t 3 /nobreak > nul
echo Opening client...
start "SecureVault Client" cmd /k "cd /d %~dp0.. && python network/socket_client.py"
echo.
echo Both windows opened. Watch the encrypted packets travel between them.
pause
